### ISSUE TITLE
ApiClient refactoring

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/Olive#100]
- Use dependency injection
- Use the new HttpClient factory stuff from .NET 2.1 instead of Polly.
- ApiResponseCache should use IFileProvider rather than hardcoding IO functionality, so that we can use S3, or a distributed cache provider by simply injecting the correct IFileProvider into it.

**Comment by iPazooki** [comment]
@PaymonK for the third part of the requirements, we can use `IFileProvider` but we must use `System.IO.FileInfo` anyway. please look at [my question here](https://stackoverflow.com/questions/52626058/how-to-use-ifileinfo-to-delete-a-file-in-asp-net-core).

Is it OK I just inject `IFileProvider` and use it for creating and editing cache files while I must use `System.IO.FileInfo` for deleting files?
