### ISSUE TITLE
"WatermarkText" doesn't work in multi-select collapsible checkbox

### ISSUE THREAD

**Issue by alaleusefi** [Geeksltd/Olive#108]
It will add a new item to list instead of adding the watermark 

Search(x => x.ClinicalSetting)
                .WatermarkText("Clinical Settings Options")
                .Control(ControlType.CollapsibleCheckBoxList);
Result:
![issue](https://user-images.githubusercontent.com/27729092/46545820-5084f680-c8bf-11e8-8d00-348e8b37457e.PNG)

**Comment by iPazooki** [comment]
@alaleusefi I believe this issue has been fixed and it's accessible by the last version of the `Olive.MVC`. if you don't experience this issue anymore, please let @PaymonK know and close this issue.
