### ISSUE TITLE
Url rewriting support for Olive

### ISSUE THREAD

**Issue by thapabhesh** [Geeksltd/Olive#116]
The only way for adding Url rewriting rule at the moment on Olive is as follows. 
```
public override void Configure(IApplicationBuilder app)
{
    var rewriteOptions = new RewriteOptions()
        .AddRewrite("^home", "website/home", skipRemainingRules: true);

    app.UseRewriter(rewriteOptions);

    base.Configure(app);

    if (Config.Get<bool>("Automated.Tasks:Enabled"))
        app.UseScheduledTasks(TaskManager.Run);
}
```

The above approach is a bit limiting in a sense that we have no access to `Context.Current.Database()` before `base.Configure(app)` is called.

**Comment by iPazooki** [comment]
@thapabhesh what's the point? I mean does this behaviour cause problem for you or is there any obstacle that prevents you from progress?

**Comment by thapabhesh** [comment]
@iPazooki I would like to compose rewrite rules based on some values retrieved from the Database. I could write my rules inside of overridden `OnStartUpAsync()` method but I think due to the precedence of middleware being registered the rules are either completely ignored or are suppressed by `app.UseMvc();` in line 108 in base Startup class.
