### ISSUE TITLE
Validation from a pop up modal remains on screen when Cancel is clicked and the pop up is closed

### ISSUE THREAD

**Issue by MohammadArifGeeksLtd** [Geeksltd/Olive#117]
On one of my projects has a pop up that contains two fields which are mandatory. Clicking Save displays the validation prompts for both fields. If I then click Cancel, the top validation disappears but the bottom validation prompt remains on screen with the pop up now closed (see screenshots)

![2018-10-11 11_48_56-window](https://user-images.githubusercontent.com/43604517/46799119-d1267580-cd4b-11e8-9130-46be8c054180.png)
![2018-10-11 11_49_08-window](https://user-images.githubusercontent.com/43604517/46799123-d388cf80-cd4b-11e8-9959-9d975b5acad3.png)

**Comment by iPazooki** [comment]
Is this issue the same as #94  ? have you updated `Olive.mvc` in the `bower.json` to the last version?

**Comment by MohammadArifGeeksLtd** [comment]
This has been tested and works correctly. Closing this issue
