### ISSUE TITLE
Can not connect to external data source

### ISSUE THREAD

**Issue by mohsens22** [Geeksltd/Olive#12]
Hello. 
In M# projects if you want to connect your M# solution to an external MSSQL data source, Olive.Entities.Data will fail.
sample connection string:
`"AppDatabase": "Database=MSharp.CNTest; Data Source=xx.xx.xxx.xxx\\Mohsensql;uid=sa;pwd=sdacsadcascdsdac;Integrated Security=SSPI;MultipleActiveResultSets=True;"`
and also
`Database=YourDatabaseName;Server=xx.xx.xxx.xxx\Mohsensql;User Id=sa;Password=sdacsadcascdsdac;Persist Security Info=False;MultipleActiveResultSets=True`

output
![image](https://user-images.githubusercontent.com/22152065/37038274-9c555576-2169-11e8-9cd0-86e7275016c9.png)
This behavior is same in all of the devices that I have tested. You can check out docker to see the same result. 
Note that it connects to the database server but refuses making a new database (Or similar actions). If you point it to an existing one, it will work(Not expected to work well; It might refuse making new tables).

**Comment by mohsens22** [comment]
Solved?

**Comment by PaymonK** [comment]
That is not an Olive issue. It's a general connection string issue.

**Comment by mohsens22** [comment]
How to get rid of this issue then?
