### ISSUE TITLE
Documentation regarding Association MaxCardinality

### ISSUE THREAD

**Issue by ChadOGeeks** [Geeksltd/Olive#123]
The documentation found at https://github.com/Geeksltd/MSharp.Docs/blob/master/Domain/Associations.md refers to setting MaxCardinality on an 'Associate' type of Association - but normally we would apply this setting on the 'InverseAssociate' type of Association.  Trying to set MaxCardinality to anything above zero on 'Associate' type of Association results in build errors whereas these do not occur when doing the same on the 'InverseAssociate' type of Association.  The documentation may need to be updated to avoid confusion.

**Comment by iPazooki** [comment]
@ChadOGeeks Thanks for your help, I have changed the documentation.
