### ISSUE TITLE
Control(ControlType.Calendar) not catered for in javascript libraries

### ISSUE THREAD

**Issue by ChadOGeeks** [Geeksltd/Olive#125]
When we set a datetime property form field or list search field to include [property].Control(ControlType.Calendar), a javascript error is thrown at runtime "Don't know how to handle date control of calendar"

It looks like the code generated by this (data-control="calendar") is not catered for in the javascript libraries included whereas another type - for example (data-control="date-picker") is.

**Comment by PaymonK** [comment]
The option to be removed from M#
