### ISSUE TITLE
TODO: Add the hangfire tasks information here. Message appears when viewing background tasks

### ISSUE THREAD

**Issue by MohammadArifGeeksLtd** [Geeksltd/Olive#127]
When I try viewing background Tasks via the Commands tab that is near the bottom of the page, I am taken to a screen stating TODO: Add the hangfire tasks information here.

I am working on an application where an item is automatically archived after a certain amount of time and the background task would enable this. Unfortunately I cannot test this as the tasks are not appearing

![2018-10-16 15_46_48-](https://user-images.githubusercontent.com/43604517/47025296-1e935000-d15b-11e8-8606-16db344f8e28.png)

**Comment by MohammadArifGeeksLtd** [comment]
Updated olive.mvc to 0.9.152 in bower.json - This issue is still occurring and I'm still seeing TODO: Add the hangfire tasks information here

**Comment by HamidTheGeek** [comment]
You won't see it with any Olive.Hangfire Nuget after 1.0.40.
