### ISSUE TITLE
On edit, text can be edited on file upload field.

### ISSUE THREAD

**Issue by JayBatesGeeks** [Geeksltd/Olive#131]
When editing an entity with a file upload, clicking the file name downloads file but the field can now be edited. The changes are not saved but the issue is that the user can edit this field.
![upload field edit](https://user-images.githubusercontent.com/44261849/47150893-098bfd80-d2d0-11e8-913d-8ee2b63af2b5.png)

**Comment by iPazooki** [comment]
@JayBatesGeeks Did you mean after uploading a file you expect that the users should just be limited to download the file and they shouldn't be able to upload it again?

**Comment by JayBatesGeeks** [comment]
@iPazooki What I mean is after uploading a file I expect that the users should be able to download the file, and should not be able to edit the text of the file name. The upload file field should be a read only / download when clicked field.

**Comment by JayBatesGeeks** [comment]
For example when i create this "Line Diagram" by setting the name and uploading a file, click save, then edit it and click the button that should download the uploaded file my cursor turns to an edit text field and i'm able to change the name of the file that has been uploaded.

**Comment by HamidTheGeek** [comment]
Fixed in 0.9.157 release.
