### ISSUE TITLE
ControlType.Switch causing UI build error

### ISSUE THREAD

**Issue by ChadOGeeks** [Geeksltd/Olive#132]
When we specify Control(ControlType.Switch) on a property of any datatype in a UI module - we get build errors stating "Switch is not relevant to BooleanProperty property." for example.

**Comment by iPazooki** [comment]
@PaymonK I believe this one is related to the M#

**Comment by PaymonK** [comment]
The warning is removed. But please make sure they work. You might need to change MvcJs for making them work.

**Comment by sara-shadmani** [comment]
@PaymonK The warning is not shown anymore but the control does not work.

**Comment by HamidTheGeek** [comment]
@PaymonK the following tag is generated for this control type which is not a valid tag.

``` html
<Switch asp-for="Property" class="form-control" autofocus="autofocus" />
```
Isn't it better to have it like the following so we can style it using CSS.
``` html
<input asp-for="Property" class="switch form-control" autofocus="autofocus" />
or
<input asp-for="Property" switch="true" class="form-control" autofocus="autofocus" />
```
