### ISSUE TITLE
Validation prompt on file upload covers the 'Choose file' button

### ISSUE THREAD

**Issue by MohammadArifGeeksLtd** [Geeksltd/Olive#136]
Can we move the validation prompt on file upload fields? Current default seems to be pointing the prompt to the bottom left. This obstructs the 'Choose file' button and the user is unable to click it to select a file to upload.

![2018-10-08 15_44_16-window](https://user-images.githubusercontent.com/43604517/47223486-51cf1c80-d3b1-11e8-8c64-8a1c316493f9.png)

**Comment by HamidTheGeek** [comment]
Fixed
