### ISSUE TITLE
Calendars are missing icons for previous and next month buttons

### ISSUE THREAD

**Issue by MohammadArifGeeksLtd** [Geeksltd/Olive#138]
When viewing calendars, the previous and next icons for the month and year are missing (see screenshot)

![2018-10-22 11_08_54-clipboard](https://user-images.githubusercontent.com/43604517/47287725-23d51c80-d5eb-11e8-8e1e-05214fcc8756.png)

**Comment by iPazooki** [comment]
Please update `olive.mvc` in the `bower.json` to the latest version, this should resolve your issue. this issue has been reported here [#26](https://github.com/Geeksltd/Olive.MvcTemplate/issues/26)

**Comment by MohammadArifGeeksLtd** [comment]
Updated olive.mvc in bower.json to version 0.9.152. This issue is no longer occurring
