### ISSUE TITLE
.Mandatory() not throwing a validation message on horizontal radio buttons

### ISSUE THREAD

**Issue by MikeTodd1** [Geeksltd/Olive#139]
On our application.  I have set both of these fields as mandatory on the UI

![horizontal radio buttons](https://user-images.githubusercontent.com/44202853/47295440-918f4180-d607-11e8-916c-c3251fb7e75d.PNG)

However on Applicants information > Personal details

![personal details](https://user-images.githubusercontent.com/44202853/47295495-ac61b600-d607-11e8-857c-78f338287a8f.PNG)

If I do not fill in these fields, it will allow the user to Save and move to the next page.  We expect the user to be shown a validation for both of these items and to not to be able to save until these are completed.

**Comment by iPazooki** [comment]
Hi @MikeTodd1  Merry Christmas
Please update `OliveJS` to the version `0.9.179` or above. there shouldn't be any problem.
