### ISSUE TITLE
Sortable Columns

### ISSUE THREAD

**Issue by mania-afshar** [Geeksltd/Olive#146]
On an entity we have added the following association AssociateManyToMany<Site>("Sites") which will create a bridging table and a calculated Task<IEnumerable<Site>> Sites. In the UI we have added a column for Sites, which cannot be sorted either by default or when we specify a sorting statement. The same code will work as expected when we don't use AssociateManyToMany.

**Comment by HamidTheGeek** [comment]
This feature is obsolete.
