### ISSUE TITLE
Edit and Archive columns merged into Select Action column

### ISSUE THREAD

**Issue by MohammadArifGeeksLtd** [Geeksltd/Olive#147]
After updating olive.mvc in bower.json to 0.9.152, The Edit and Archive columns have become merged to a Select Action drop down.

Speaking to our PM and tech lead developer, this is not a feature we want on our project as it deviates from visualspec wireframes. Can we revert this and if a project requires this, write up documentation on how to go about implementing this?
![2018-10-30 11_29_53-window](https://user-images.githubusercontent.com/43604517/47715312-53150a80-dc37-11e8-8205-de099307a3c1.png)

**Comment by iPazooki** [comment]
@MohammadArifGeeksLtd I have fixed your reported issue, but please wait for the new release that would be `0.9.153` and here is [Documentation](https://github.com/Geeksltd/MSharp.Docs/blob/master/how-to/MergeColumns.md)
