### ISSUE TITLE
Javascript files do not load correctly on Ipads and IPhones

### ISSUE THREAD

**Issue by anaSelegova2018** [Geeksltd/Olive#152]
The carousel items do not work as expected. The main issue javascript files are not loaded correctly for iphones and ipads. For our project it happens for, drop down menus, sidebar menus and js code to change onclick class names.

**Comment by HamidTheGeek** [comment]
This issue was not related to the framework. In fact, a new syntax of javascript been used in reference.js which is not supported by the older version of safari.
