### ISSUE TITLE
Login  error - Olive.mvc

### ISSUE THREAD

**Issue by mania-afshar** [Geeksltd/Olive#160]
We receive the following error after updating to the latest version of Olive.mvc in bower.json (0.9.154)

![capture](https://user-images.githubusercontent.com/41914368/48135076-c9e38080-e293-11e8-89d1-f5e34838548b.png)

**Comment by iPazooki** [comment]
@mania-afshar please add `bootstrap-select`, you can found documentation [here](https://github.com/Geeksltd/Olive/blob/master/docs/ChangeLog.md#05-nov-2018)

**Comment by HamidTheGeek** [comment]
It's fixed in Olive.mvc in bower.json (0.9.156)
