### ISSUE TITLE
Mandatory() not showing validation message for AutoComplete fields

### ISSUE THREAD

**Issue by ShivSGeeks** [Geeksltd/Olive#183]
In our application, we have set a field as mandatory and visible based on criteria.

![autocomplete mandatory issue - ui](https://user-images.githubusercontent.com/45559659/49368936-03b77380-f6e8-11e8-8007-2ff6bd67e875.png)

However, when clicking Save on the page containing this field:

![autocomplete mandatory issue - application](https://user-images.githubusercontent.com/45559659/49368935-03b77380-f6e8-11e8-8b85-cfcb2b9f63e4.png)

The validation message does not appear as it should. This currently allows the user to save the changes despite the field being both visible and a mandatory requirement.

Adding a control attribute to the field or removing its visibility rule would show a validation message. But this will only work when its text field is empty. As soon as any text is entered, the validation message does not appear.

For reference, the validation works correctly if the field was changed to a dropdown list.

**Comment by iPazooki** [comment]
Hi @ShivSGeeks,  _Merry Christmas_

You are experiencing this issue because you have used `.VisibleIf()` method. actually, by using this method M# will not generate `[Required]` for autocomplete property and in the UI you won't have any validation.

**Comment by HamidTheGeek** [comment]
It has been fixed
