### ISSUE TITLE
Cannot access hangfire dashboard on Published Olive projects

### ISSUE THREAD

**Issue by MohammadArifGeeksLtd** [Geeksltd/Olive#184]
With Automated tasks disabled, I can access the URL **/cmd/scheduled-tasks** and see tasks appearing from TaskManager.cs. When I try to access the URL **/hangfire** there is a Page can't be found error displaying.

This issue occurs when accessing the Published version linked via my local IIS setup. When I run the application via Visual Studio, the **/hangfire** dashboard works fine. Would it be possible to make the hangfire dashboard available for published projects?

**Comment by PaymonK** [comment]
@HamidTheGeek  and @MohammadArifGeeksLtd  it's now changed in M# and Olive.
Now, the tasks will be registered regardless of the `Config.Get<bool>("Automated.Tasks:Enabled")` value.

When invoking `/cmd/scheduled-tasks` we will show only the task name and a link reading `Execute`.
