### ISSUE TITLE
AjaxRedirection and Css loading

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/Olive#187]
When redirecting from one page to another using the Ajax framework, it will replace the <main> body of the target page. If within that, there is a CSS reference (i.e. a `<style src=... />` tag) then the browser will automatically request it after loading the new `<main>` html.

This means that for a moment, the `<main>` content will be loaded without its CSS. This leads to some  annoying page jumps, as well as slow rendering.

To fix it, the TS code that is processing the new `<main>` tag should look for css references inside it:
- Load the CSS on to the window first
- Remove the css tag from the html
- Then add the new `<main>` html.

**Comment by iPazooki** [comment]
@PaymonK Thanks, I will deal with it as you have mentioned. good idea!
