### ISSUE TITLE
Multiselect Dropdown Error

### ISSUE THREAD

**Issue by parisvithoulkas** [Geeksltd/Olive#197]
[Multiselect_Error.zip](https://github.com/Geeksltd/Olive/files/2680757/Multiselect_Error.zip)

The above video can be played using IE.
As shown in the video if we have a multiselect dropdown box without any data added yet then when we search for an item we are shown an error message saying "No Results Matched". However, if we navigate away from the dropdown and then come back, the same error is being displayed even if we have cleared the text from the field. The error message will disappear if we refresh the page but it might be better for it to disappear as soon as we navigate away from the dropdown.

**Comment by iPazooki** [comment]
@parisvithoulkas as far as I can see, this issue only happens when we don't have any data for _CollapsibleCheckBox_. but there should be at least one item in each collapsible checkbox, so in the real world, this will not happen.

**Comment by HamidTheGeek** [comment]
It should be raised in [Olive.MvcJs](https://github.com/Geeksltd/Olive.MvcJs) if it is not sorted yet.
