### ISSUE TITLE
Do not set system32 as working directory

### ISSUE THREAD

**Issue by Hatef-Rostamkhani** [Geeksltd/Olive#234]
https://github.com/Geeksltd/Olive/blob/459051e49a32bdf0af370ae57a7275cd1873e752/Olive/-Extensions/FileInfo.cs#L89

based this code, when you want to found nuget by where.exe you set working directory as c:\windows\system32 and nuget not found so I have an error to find nuget.exe, if you set empty nuget.exe was found

OliveSolution.cs method RestoreNuget() called i have a error when called WindowsCommand.FindExe("nuget")

you can change it or change the method parameters and set the working directory

WorkingDirectory = @this.Directory.FullName.ToLower().Contains("system32") ? string.Empty : @this.Directory.FullName,

**Comment by iPazooki** [comment]
@Hatef-Rostamkhani Thanks for your solution, if you don't mind, please create a Pull Request that contains your suggested changes and then @PaymonK  will decide about it.

**Comment by Hatef-Rostamkhani** [comment]
Thanks, I sent a pull request
