### ISSUE TITLE
OutboxDevCommand - Can't download the attachment 

### ISSUE THREAD

**Issue by AitzazTheGeek** [Geeksltd/Olive#237]
When downloading the attachment from Outbox command page , An exception is raised "ThrowResponseAlreadyStartedException (Status code can't be set because response has already started)"

With some investigation in the issue found out that DevCommandMiddleware is setting the status code to 302 (redirect) after the response has been written by EmailTestDevCommand.
![responsealreadywritten](https://user-images.githubusercontent.com/42996479/52051610-f97cee80-254b-11e9-83ac-990ca8b9ce58.png)
![throwresponsealreadystarted](https://user-images.githubusercontent.com/42996479/52051617-000b6600-254c-11e9-8d67-e4235255f7b7.png)

**Comment by HamidTheGeek** [comment]
Hi @AitzazTheGeek, 
I guess it has been fixed, am I wrong?

**Comment by AitzazTheGeek** [comment]
@HamidTheGeek  yes it is.
