### ISSUE TITLE
OnChange event causing the page to scroll up.

### ISSUE THREAD

**Issue by SkirmantasSutkus** [Geeksltd/Olive#239]
If we are using a .ReloadOnChange on a form, or opening a pop-up, the page is going to automatically be scrolled to the very top on those events.

This means that having a control element or a pop-up button like that in a longer page is causing real bad user experience of having to scroll back down after the "reload" event and our client is dissatisfied with it.

Hamid suggests it has to do with the Olive.Mvc JS. 

This is fairly easy to replicate, but hard to give an example in pictures, so feel free to contact me if you need more info.

**Comment by HamidTheGeek** [comment]
Fixed
