### ISSUE TITLE
Full page refresh on list sorting

### ISSUE THREAD

**Issue by WaseemGeeks** [Geeksltd/Olive#241]
When sorting the list, the whole page is refreshed with sort column name appended in query string in url. This is causing the whole page controls to clear and makes a visible UI issue for end user. Can we add functionality to ensure the complete page isn't refreshed?

**Comment by HamidTheGeek** [comment]
Hi @PaymonK,
In order to support this feature, we need to change the implementation of the list pages. In fact, the list should be rendered after the page is loaded using an ajax call. Is it something that we want to support?
