### ISSUE TITLE
Validation tooltip messages not showing for mandatory radio button fields

### ISSUE THREAD

**Issue by ShivSGeeks** [Geeksltd/Olive#243]
In the Model, we have set a property as mandatory:

![olive-radio-01](https://user-images.githubusercontent.com/45559659/53417026-96586d80-39cc-11e9-9676-56c05a7a28a7.png)

In the form for add/editing, we have set the control type for this property to be horizontal radio buttons:

![olive-radio-02](https://user-images.githubusercontent.com/45559659/53416971-7c1e8f80-39cc-11e9-8e2b-0bc1766ffd28.png)

However, when we click Save without anything entered/selected for this field, no validation tooltip message appears for it. It will instead only appear in a pop-up/alert message box, once other required fields have been filled in:

![olive-radio-03](https://user-images.githubusercontent.com/45559659/53416989-83de3400-39cc-11e9-83bb-6af92e048259.png)

This is also happening when the control type is set to vertical radio buttons, as well as when attempting to add a .Mandatory() or .RequiredValidationMessage() parameter for it.

But when it is set to, for example, a dropdown list or autocomplete field, the tooltip message will appear without issue.

This was also checked with the latest Olive packages.

**Comment by iPazooki** [comment]
Hi @ShivSGeeks  

This issue is related to using `VisibleIf()` method. I believe if you remove this method it will work properly.
if this property is mandatory it should be filled in any cases, but you just want to make it mandatory if it meets some criteria. so I reckon you should change your logic a little bit.

**Comment by ShivSGeeks** [comment]
Hey @iPazooki 

I had a look into this again based on what you suggested and unfortunately, this is not the case.

Even after removing all extra parameters for the field (including VisibleIf() and CustomDataSave()) and only just keeping the field being displayed as radio buttons, the validation tooltip message still does not appear on the form. The closest where you get a validation message for the field is only in a pop-up box when saving.

![olive-radio-04](https://user-images.githubusercontent.com/45559659/53644257-0fa2cb00-3c2e-11e9-9f9d-808efcd34378.png)
![olive-radio-05](https://user-images.githubusercontent.com/45559659/53644260-116c8e80-3c2e-11e9-8747-4973fac2b506.png)

If the field was using the default control type or a dropdown/autocomplete field, the tooltip validation message appears without issue:

![olive-radio-06](https://user-images.githubusercontent.com/45559659/53644458-8f309a00-3c2e-11e9-937a-03a73cc4a5ec.png)

This is still happening, even with new Olive updates made available during the past couple of days.

**Comment by ShivSGeeks** [comment]
After discussing with @iPazooki and after further investigations into this, it was confirmed that the issue was the result of how the styling was carried out for the custom radio buttons.

The item(s) containing the ".handled" class name must not be hidden from view, in order for the validation tooltip messages to appear when clicking Save.

Consider this now resolved.
