### ISSUE TITLE
Page freezes when inactivity threshold is met

### ISSUE THREAD

**Issue by RossSilcott** [Geeksltd/Olive#244]
When the inactivity time has been reached the screen becomes inactive rather than going straight to the login screen. 

Also page links become inactive if they have ajax redirects on them

**Comment by iPazooki** [comment]
Hi @RossSilcott  thanks for raising up this issue.
Do you have this issue on the micro-services or MC# applications?

**Comment by RossSilcott** [comment]
MC# application

**Comment by RossSilcott** [comment]
Hi. Just checking if this is being looked at, at the moment and if a fix is on the way soon.
