### ISSUE TITLE
Text inputted into AutoComplete field not automatically selecting result with exact matching text by default

### ISSUE THREAD

**Issue by ShivSGeeks** [Geeksltd/Olive#245]
If the user enters the exact text of a matching result in the AutoComplete field (e.g. when using an auto fill extension to populate the form, or if they enter matching text of an item that they had selected previously) and clicks Save without selecting that item from the results list (or if they select it, then modify the text in the field before saving), it will not select/store the matching result upon validating/saving. It will also throw a validation exception regarding the field, if it is mandatory.

Unless it was originally intended to be part of the original implementation, can we have it so that when the user enters text in the AutoComplete field, if it finds a result that exactly matches the inputted text, it will automatically select/assign that item by default when saving, but still allow the user the option to choose from any other related result(s) from the list?

**Comment by HamidTheGeek** [comment]
It has been fixed in [release 0.9.199](https://github.com/Geeksltd/Olive.MvcJs/releases/tag/0.9.199) of Olive.MvcJs
