### ISSUE TITLE
FileUpload "data" attributes is not working with AjaxRedirect. (e.g: data_text)

### ISSUE THREAD

**Issue by atirnaveed** [Geeksltd/Olive#249]

**Comment by atirnaveed** [comment]
Example : data_text replace the text of button 
![image](https://user-images.githubusercontent.com/17332223/54750140-9ebc5680-4bce-11e9-8900-895facbe584d.png)
It should display like this
![image](https://user-images.githubusercontent.com/17332223/54750174-b7c50780-4bce-11e9-9689-67af67411c23.png)
but this only works when you refresh the page it will not work with AjaxRedirect.

**Comment by HamidTheGeek** [comment]
Hi Atir,

The data attributes should be in this format `data-text="test"` while you have it like `data_text`. Could you please give it a try and let me know if still had any issue?

**Comment by atirnaveed** [comment]
Hi Hamid,

This is becuase you can't give `-` in htmlAttribute it will render as `_`  in html.
Code : 
![image](https://user-images.githubusercontent.com/17332223/54756454-2c547200-4be0-11e9-9eb1-bc0722b3230a.png)
Html Render :
![image](https://user-images.githubusercontent.com/17332223/54756704-b3094f00-4be0-11e9-854b-b407055e5d4b.png)

**Comment by HamidTheGeek** [comment]
Fixed in `v0.9.204`.
