### ISSUE TITLE
"All" option not selecting/deselecting all options in list

### ISSUE THREAD

**Issue by WaseemGeeks** [Geeksltd/Olive#255]
![SelectAllOption](https://user-images.githubusercontent.com/44066382/55004169-9fd7f400-4fd1-11e9-8726-b4afb6b92979.PNG)

clicking on "All" option doesn't select/deselect all options in the list.

**Comment by HamidTheGeek** [comment]
Hi @WaseemGeeks ,
The `All` item is actually an item just like the other items. Either the data source for your multi-select is wrong or this item logically behaves like like the time you have selected all the items. In both scenarios multi-select works as it is expected.
