### ISSUE TITLE
Refresh.Ajax not updating collapsible checkbox list with new item

### ISSUE THREAD

**Issue by ShivSGeeks** [Geeksltd/Olive#256]
In our application, we have a modal page that allows the user to add a new contact (for a company selected in the parent form).

![Collapsible-checkbox-01](https://user-images.githubusercontent.com/45559659/55016497-c81e1d80-4fe6-11e9-8c92-ebe66bbf4c25.png)

When clicking Save, it closes the modal and carries out an Ajax refresh, which updates the autocomplete fields with the new item without issue.

![Collapsible-checkbox-02](https://user-images.githubusercontent.com/45559659/55016552-e97f0980-4fe6-11e9-8eaa-03063b13cdd3.png)

However, the Ajax refresh does not appear to be working with regards to collapsible multi-checkboxes.

![Collapsible-checkbox-03](https://user-images.githubusercontent.com/45559659/55016601-00bdf700-4fe7-11e9-9336-05199b07d1cd.png)

If the page was refreshed fully (or if a ReloadOnChange() action was called), it then shows the new item in the list.

![Collapsible-checkbox-04](https://user-images.githubusercontent.com/45559659/55016673-264b0080-4fe7-11e9-9d4a-bbe5d7e2858f.png)

**Comment by HamidTheGeek** [comment]
Hi @ShivSGeeks, there is a possibility for this issue to be a duplication of [this](https://github.com/Geeksltd/Olive/issues/257). Or in fact, the mentioned one is the duplication. Could you please check to see if it has been fixed?

**Comment by ShivSGeeks** [comment]
Checked with @HamidTheGeek and confirmed that updating the olive.mvc yarn package to latest version fixes this (currently 0.9.208 at the time of this message).

Issue resolved and closed.
