### ISSUE TITLE
Page not refresh when use Refresh.Ajax in Model popup

### ISSUE THREAD

**Issue by atirnaveed** [Geeksltd/Olive#257]
Hi ,
There is a porblem while closing the model-popup with Refresh.Ajax.
![image](https://user-images.githubusercontent.com/17332223/55164982-7bf8e780-5164-11e9-947e-fbf53cae2850.png)
It's generate error on formAction.ts at line 135.
![image](https://user-images.githubusercontent.com/17332223/55165058-a185f100-5164-11e9-8025-b31bbd224e7c.png)
![image](https://user-images.githubusercontent.com/17332223/55165079-ad71b300-5164-11e9-9681-836d8e26c83f.png)

**Comment by HamidTheGeek** [comment]
Hi @atirnaveed,
Fixed in `v0.9.203`. Please let me know if it is not.
