### ISSUE TITLE
Issue in decryption while using other functions for Database rather than GetList or Get

### ISSUE THREAD

**Issue by atirnaveed** [Geeksltd/Olive#260]
Hi,
Decryption is not working with different methods of Database, it's working fine with GetList, Get method but not working with Of, I think it should work same with all methods.
Using **Of** :
![image](https://user-images.githubusercontent.com/17332223/55804299-e9493880-5ad3-11e9-8cfe-634a10c123c9.png)
Using **GetList** :
![image](https://user-images.githubusercontent.com/17332223/55804412-27def300-5ad4-11e9-9015-b9426a4fede7.png)
Using **Get** :
![image](https://user-images.githubusercontent.com/17332223/55804606-8efca780-5ad4-11e9-8d04-f0e9af3764eb.png)

**Comment by HamidTheGeek** [comment]
Will fixed with the new release.
