### ISSUE TITLE
AuditEvents and PredictableGuidEnabled setting causes duplicate key errors

### ISSUE THREAD

**Issue by ChadOGeeks** [Geeksltd/Olive#264]
When appsettings.json is configured to have Audit insert, update and delete actions and data set to true and you also have the PredictableGuidEnabled setting (for Pangolin) set to true, duplicate key errors are thrown when updating entities (in our case it was when saving users)

[ExceptionDetails.txt](https://github.com/Geeksltd/Olive/files/3240700/ExceptionDetails.txt)

**Comment by HamidTheGeek** [comment]
Hi @ChadOGeeks,

When you enable the predictable Ids in your settings you should make sure that the database is dropped whenever the process is restarted. Are you sure this is not your issue?

**Comment by ChadOGeeks** [comment]
Thanks Hamid, after checking this again more recently I am not able to recreate the issue.   Closing for now
