### ISSUE TITLE
Missing await in cascade delete logic

### ISSUE THREAD

**Issue by AliWardere** [Geeksltd/Olive#267]
I have a one-to-one relationship between entities A and entity B. Entity B is cascade deleted when entity A is deleted.

Entity B: 
`Associate<A>("A").OnDelete(CascadeAction.CascadeDelete).Unique().Mandatory();`

Cascade Delete Logic Generated on Entity A:
` async Task Cascade_Deleting()
        {
            await ValidateCanBeDeleted();         
            if (Task<B> != null)
            {
                await Database.Delete(await Detail);
            }
        }`

The conditional `Task<B> != null` is missing an await. This is a problem because, on the creation of Entity A, Entity B is null.

Can we add an await in the conditional, please?

**Comment by HamidTheGeek** [comment]
It seems to be fixed in recent versions.
