### ISSUE TITLE
ReloadOnChange causing an issue with the save button

### ISSUE THREAD

**Issue by RubenVegaPoblete** [Geeksltd/Olive#269]
It seems that when you enter a value into a textbox that is set to reload on change and then immediately click the save button it will instead reload and will only accept the button press on the next click. If you enter the value, click off the textbox and then click the button it works.

**Comment by HamidTheGeek** [comment]
Hi @RubenVegaPoblete,
Thank you for rasing this issue, but I believe it is not a problem. When you have a `ReloadOnCHange` it means that there is a logic which needs to be done before saving the page. Sometimes the logic could be ignored but sometimes not. As the framework should cover all the scenarios the current behavior looks fine to me. Please, let me know if you have any reason to do not agree with me.
