### ISSUE TITLE
Paging issue with Search 

### ISSUE THREAD

**Issue by atirnaveed** [Geeksltd/Olive#281]
Hi,

There is an issue while searching, if you're on last page and filter anything which end in first page it shows empty list, it should show the data from starting if there any search data less than the paging.

Thanks.

**Comment by HamidTheGeek** [comment]
Hi @PaymonK,

Although it is nice to take the user to the last page (or even first page) when there are records to show them when they are on the wrong page number, the current implementation is not unusual.

Should I implement this change request?
