### ISSUE TITLE
Slow UI build when string based column visibility rule combined with visibility rule on same item

### ISSUE THREAD

**Issue by ChadOGeeks** [Geeksltd/Olive#284]
We've found that when we have something like this:

            ButtonColumn("Unarchive")
              .VisibleIf("item.IsArchived)
              .ColumnVisibleIf("info.Pricing.StatusId == PriceStatus.Draft")

The UI project takes about 4 times longer to build. To get our UI project build time reduced dramatically, we have had to temporarily change this to:

            ButtonColumn("Unarchive")
              .VisibleIf("item.IsArchived && info.Pricing.StatusId == PriceStatus.Draft")
              //.ColumnVisibleIf("info.Pricing.StatusId == PriceStatus.Draft")

Please could you assist with identifying and resolving the issue with the slow building of UI when this type of combined column string based column visibility rule and visibility rule exist on same element

**Comment by HamidTheGeek** [comment]
Hi @ChadOGeeks, 
Thank you for reporting this. As it is related to M# I moved it to the task system.
