### ISSUE TITLE
Azure Blob files missing document extension

### ISSUE THREAD

**Issue by mz-andrewpotts** [Geeksltd/Olive#296]
# Problem
We migrated from the DiskBlobStorageProvider (files stored on the server's local disk) to AzureBlobStorageProvider (Azure blobs).

In doing so, we copied the files that already existed to an identical folder structure in Blob.
However, there is an incompatibility between the two providers. This means that previously saved files cannot be read - it results in the BlobNotFound exception. 

# Analysis
The DiskBlobStorageProvider [appends the file extension](https://github.com/Geeksltd/Olive/blob/3f162dd34b5c6e7c91422005f07920361fc985af/Olive.Entities/Blob/DiskBlobStorageProvider.cs#L30) but AzureBlobStorageProvider [doesn't](https://github.com/Geeksltd/Olive/blob/3f162dd34b5c6e7c91422005f07920361fc985af/Olive.Entities/Extensions/BlobExtension.cs#L18). 

It would be good for both to be identical so there is a seamless migration between the two providers.

# Workaround
I have created a copy of the Olive.Blob.Azure project and replaced all lines that execute:
`var key = document.GetKey();`

with a function that returns:
`document.FolderName + "/" + document.OwnerId() + document.FileExtension;`

but it would be good to get this fix pushed into the main codebase.

**Comment by m-sadegh-sh** [comment]
@mz-andrewpotts Sorry for the delayed response. Please recheck your issue against the latest version of the Azure package and if you encounter the problem, we'll appreciate accepting your pull request.
