### ISSUE TITLE
Model binding validation for entities.

### ISSUE THREAD

**Issue by HamidTheGeek** [Geeksltd/Olive#59]
If you had an Entity as a parameter in your Action all its property would be validated (Including calculated ones). As Olive has its own binder for entities it would be unnecessary.

**Comment by iPazooki** [comment]
Hi, @HamidTheGeek 
 Though this issue is for about 2 weeks ago, is this issue active yet or it has been solved?

**Comment by HamidTheGeek** [comment]
Hi @iPazooki,
I believe it has not been solved yet.

**Comment by iPazooki** [comment]
@HamidTheGeek  Could you explain more about your purpose? I mean you suppose Olive binder is unnecessary in this scenario?

**Comment by HamidTheGeek** [comment]
Olive binder retrieves the entity from the database based on the passed id. Then it tries to validate the entity's property which is unnecessary (They are not passed by the client). So the Olive binder is necessary, unlike the validation.

**Comment by iPazooki** [comment]
@HamidTheGeek  To trace this issue I put logger everywhere that was related to the _Validation_ but just when Entity gets saved I see validation occur and this manner is true but in **Get()** method I didn't see any validation occur!

This issue maybe has got fixed or maybe I was not able to find it yet.

Could you tell me where do you think this validation happens for **Get**? I mean in which file or method!
