### ISSUE TITLE
Creating Temp Database

### ISSUE THREAD

**Issue by mania-afshar** [Geeksltd/Olive#60]
Occasionally, the Execute method will fail on the  try { Execute(script); } line, where the create database sql files cannot be run because of the following error:

> Timeout expired. The timeout period elapsed prior to completion of the operation or the server is not responding.

The full stack trace has been attached.  [timeout error stack trace.txt](https://github.com/Geeksltd/Olive/files/2241864/timeout.error.stack.trace.txt)

This will then cause the following error:  [reset db issue](https://user-images.githubusercontent.com/41914368/43408040-3b5eff2a-9418-11e8-871d-d1825cde1de0.png)

This happens when the application is restarted. In the TestDatabaseGenerator.cs class, EstablishDatabaseFromScripts() gets called 

```
bool EstablishDatabaseFromScripts()
        {
            if (!DropExisting)
                if (Server.Exists(TempDatabaseName, DatabaseFilesPath.FullName))
                    return false;

            CreateDatabaseFromScripts();
            return true;
}
```

Server.Exists(TempDatabaseName, DatabaseFilesPath.FullName) returns true because the database was created with the correct name before the Execute method above failed. However, none of the tables was generated. At this point the only option is to manually delete the database in MSSMS which slows down the testing process.

**Comment by iPazooki** [comment]
@mania-afshar I'm struggling to experience this issue but I'm not successful. I run the Hub project and select Restart DB from small widget which is located at the bottom of the page. but there is no issue!

Could you explain what is your scenario?

**Comment by mania-afshar** [comment]
Thank you for your response.

As you say, resetting the database manually using the testing widget works fine.

The issue we experience happens when we test using [Sanity Hub](https://sanityhub.com/). I'm attaching the error screen that we receive, after which we receive the unhandled exception 
![could not execute sql file cidt](https://user-images.githubusercontent.com/41914368/43721409-93fc2690-998a-11e8-9b1a-1fd439dc3ae2.PNG)
page. 

This happens often, but not every time and we haven't been able to establish a pattern it happening.
