### ISSUE TITLE
Modal without iFrame

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/Olive#61]
@iPazooki 

Currently modal windows always open in an iframe. That is sometimes useful, when the modal page is complex and requires its own window context. But that's rare.

In Olive, by default, modal windows should be loaded using Ajax, and the same ajax lifecycle that we have for full pages should apply to them. This will improve speed, usability and design. It can be tested in the MindMap project.

But the user should have the option to use iframe by using:

`<a href='...' target='$modal' data-mode="iframe">...</a>`

**Comment by iPazooki** [comment]
Done, please close this issue @PaymonK

**Comment by iPazooki** [comment]
@PaymonK  please close this issue
