### ISSUE TITLE
Issue with outbox rendering on EmailTestService

### ISSUE THREAD

**Issue by thapabhesh** [Geeksltd/Olive#63]
Attachments is displayed as **System.Threading.Tasks.Task`1[System.String]** even though we do not have attachment.

![attachments](https://user-images.githubusercontent.com/36714740/43654347-d929201e-9742-11e8-8ca5-1df6f1cc97ba.png)

**Comment by PaymonK** [comment]
Fixed in Olive.Email (nuget) version 1.0.37
