### ISSUE TITLE
Updating project .gitignore rule

### ISSUE THREAD

**Issue by thapabhesh** [Geeksltd/Olive#64]
We need to update the .gitignore file to track MSharp.DSL.runtimeconfig.json

```
M#/lib/netcoreapp2.1/*
!M#/lib/netcoreapp2.1/MSharp.DSL.runtimeconfig.json
```

The above rule should be updated to the following

```
M#/lib/*
!M#/lib/netcoreapp2.1/
M#/lib/netcoreapp2.1/*
!M#/lib/netcoreapp2.1/MSharp.DSL.runtimeconfig.json
```

**Comment by iPazooki** [comment]
@thapabhesh  I couldn't find `MSharp.DSL.runtimeconfig.json` in the `.gitignore` of **Olive** project, but it's available in other projects, ex: **Hub**. are you sure about it?

**Comment by thapabhesh** [comment]
@iPazooki Thank you for quick reply. I think the issue is related to [Olive.MvcTemplate](https://github.com/Geeksltd/Olive.MvcTemplate/issues/24) so I have raised the issue on that project. Sorry for confusion.

**Comment by iPazooki** [comment]
@PaymonK  please close this issue.
