### ISSUE TITLE
Autocompletes - List of Strings as DataSource

### ISSUE THREAD

**Issue by mania-afshar** [Geeksltd/Olive#65]
I have a CustomField on first and last names on a form, as autocomplete. The data source comes from users that have previously registered.  In my change event handler, info.LastName_Text will have the expected value but not info.LastName which will always be null.

The second issue is selecting a value on the UI which does not always work. Once we start typing, we see the expected result but clicking on the value we want or using the Enter key work works only occasionally. 

We are not experiencing either of those issues when the data source is on another entity.

**Comment by iPazooki** [comment]
#@mania-afshar , do you use _Hub_ project or stand-alone using _MVC template_? I need more information, please if you don't mind send me an email containing some pictures about this issue. 

> We are not experiencing either of those issues when the data source is on another entity.

you mean when you use it for another entity autocomplete work correctly? if you experience this issue in just some cases please send me related screenshots with more detail. actually, I didn't experience any issue so far.

EMAIL: **iPazooki@gmail.com**

**Comment by mania-afshar** [comment]
Thank you for your response. 

This is a standalone project using the MVC template and I have sent you samples of the code that we're using along with a further explanation of the issue.
