### ISSUE TITLE
.Mandatory() method 

### ISSUE THREAD

**Issue by mania-afshar** [Geeksltd/Olive#66]
On a form, we want to mark some of the fields as mandatory although they are not mandatory in the model. The documentation for .Mandatory() method explains that this should override the the behaviour set in the model however, at the moment this is not happening. 

Please see the attached screenshot which shows the the required-item css class gets added to the HTML container to show a red asterisk next to the element, however, there is no validation added for this so that when we click on the save button only fields that are mandatory in are our model have a validation.

![mandatory](https://user-images.githubusercontent.com/41914368/44092541-a739e12c-9fc8-11e8-95ae-8b2d6fd0a631.PNG)

**Comment by iPazooki** [comment]
@mania-afshar  Yeah, if you put validation on the #UI project, it will disable UI validation and we just have server-side validation. I will deal with it. Thanks for reporting.

**Comment by PaymonK** [comment]
I think you haven't compiled the Website project. Check if [Required] attribute is added to the ViewModel. That's what the validation scripts work from.

**Comment by mania-afshar** [comment]
This is happening for drop downs and auto-completes. It works as expected for simple inputs of type text.
The [Required] attribute is being generated. 

For drop downs at least this caused by the Chosen plug in which adds style="display: none;" to the select input; jQuery validate ignores hidden elements

For auto-completes, the input with the data-val-required attribute is also hidden, again causing this to be ignored.

**Comment by iPazooki** [comment]
@mania-afshar  yeah, you are right, this problem is because of using _chosen_ library. but I have found the solution [here](https://github.com/harvesthq/chosen/issues/515#issuecomment-55901946)

the problem is all our generated select element is mandatory, irrespective of you have made it or not! if I found a solution for this, I'll fix this issue in Olive.MvcJs.

**Comment by iPazooki** [comment]
@mania-afshar by updating to the latest version this issue will be solved.

**Comment by mania-afshar** [comment]
Thank you, @iPazooki. Users can no longer submit the form without setting all mandatory fields but they don't receive any validations that lets them know they need to fill those fields in. Please see attached screenshots. The first one (Company name) is marked mandatory on the model, the second (Visitor type) is not.

![validation](https://user-images.githubusercontent.com/41914368/45287787-0e93ab00-b4e1-11e8-9a69-c9de02b68580.PNG)
![validation 2](https://user-images.githubusercontent.com/41914368/45287792-10f60500-b4e1-11e8-8338-f7f7e56b0ca9.PNG)

**Comment by iPazooki** [comment]
@mania-afshar you are welcome. but Paymon fixed this issue and I was aware of this problem as I mentioned before here!

Did you update all your Olive and M# nuget packages?

**Comment by mania-afshar** [comment]
Yes, all packages have been updated.

**Comment by iPazooki** [comment]
@mania-afshar so, generated **select** element here should be always **Required** irrespective of you set it Mandatory or Not in the #UI project.
if you don't mind please give me a picture when you have set _Visitor type_ property optional but here is mandatory. I need see generated HTML.

Thanks in forward.

**Comment by iPazooki** [comment]
@mania-afshar Please look at these two pictures, I tried to replicate your scenario but every thing is OK for me!

here **Urgency** is not mandatory.
![1](https://user-images.githubusercontent.com/1321544/45295241-3bf94c80-b513-11e8-822f-aeda794e03b1.PNG)

here **Urgency** is mandatory.
![2](https://user-images.githubusercontent.com/1321544/45295297-6b0fbe00-b513-11e8-8f8b-8e7131b15e8b.PNG)

**Comment by iPazooki** [comment]
@mania-afshar By the way, please make sure in your `bower.json` this package is referenced:
`jquery-validation-bootstrap-tooltip`

I mean your bower should be something like this:
![3](https://user-images.githubusercontent.com/1321544/45295510-32241900-b514-11e8-94c0-9d2f06e21e84.PNG)

**Comment by iPazooki** [comment]
@mania-afshar Hi Mania, did you still have this issue?

**Comment by iPazooki** [comment]
@mania-afshar Yeah, that was me, I myself wrote that. I mean on that time there was an issue with **jQuery-UI** because at that time we load all **jQuery-UI modules** and now there is no issue. I mean I have recently fixed that. so don't worry, you can now safely use it.
Thanks for letting me know, I will add this to ChangeLog.

**Comment by iPazooki** [comment]
@mania-afshar we have updated Change Log, Thanks for letting me know and please if you still have this issue let me know.
[https://github.com/Geeksltd/Olive/blob/master/docs/ChangeLog.md#12-sep-2018](https://github.com/Geeksltd/Olive/blob/master/docs/ChangeLog.md#12-sep-2018)

**Comment by mania-afshar** [comment]
@iPazooki I updated the packages according to the above change log. I'm afraid that disabled all the validations in the application so for examples in the code section below, we would end up with error screens rather than a validation message to the user.

`try
                {
                    if (!await SaveInDatabase(info)) return JsonActions(info);
                }
                catch (Olive.Entities.ValidationException ex)
                {
                    return Notify(ex.Message, "error");
                }`

I tried that with the latest versions of the Olive NuGet packages.

**Comment by mania-afshar** [comment]
The issue has been fixed with the latest updates and can be closed. Thank you.
