### ISSUE TITLE
Unit tests for Olive Data

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/Olive#67]
Create a comprehensive list of unit tests for Olive Data framework.

- Cover all database Apis
- SQL Server and My SQL
- Against actual sample database

**Comment by iPazooki** [comment]
@PaymonK Should I create a separate test project like **Olive.Entities.Data.SqlServer.Test** and add some initial classes there and let developers reference this project using Nuget packges? 
so developers can use these classes in their own test project?
or these tests are just meant to be used in Olive project and it just checks Olive methods?

**Comment by PaymonK** [comment]
No we need the tests to be written against the main API, and then for test execution, we should use a wrapper to run the test twice, once against SQL and once against MySQL.

**Comment by PaymonK** [comment]
The test libraries you write here will not be used in other projects. This is specifically to test Olive itself.
