### ISSUE TITLE
Bad overflow on modal windows

### ISSUE THREAD

**Issue by dlra** [Geeksltd/Olive#69]
I have a list module with some custom markup. When the content goes over a certain limit, a link to a modal window appears. Within this modal window is a view module, within which the whole of the list item may be viewed without truncation. The issue is that the modal window does not set to the correct dimensions meaning the content is obscured. See images> I have included the console error on opening the popup.

More generally, we are having issues with popups overflowing for some reason or another (e.g., many options picked on a multi-select field) and content being obscured, e.g., buttons being no longer visible and therefore not clickable.

![popup-link](https://user-images.githubusercontent.com/15689258/44538769-408fc980-a6fa-11e8-9396-fe1ea0400d55.png)
![popup](https://user-images.githubusercontent.com/15689258/44538773-45547d80-a6fa-11e8-88d8-0be835ce418e.png)
![console-error](https://user-images.githubusercontent.com/15689258/44538774-471e4100-a6fa-11e8-8e87-32e37af8b121.png)

**Comment by iPazooki** [comment]
@dlra  Thanks for informing. I will deal with it in no time.

**Comment by iPazooki** [comment]
@dlra  it seems you are using the older version of **Olive.MvcJs**. please update it to latest version [0.9.132](https://github.com/Geeksltd/Olive.MvcJs/releases) and let me know if you still experience this issue or not.

**Comment by iPazooki** [comment]
@dlra Do you still have this issue even after updating to the last version? I can't replicate this issue.

**Comment by iPazooki** [comment]
@PaymonK I didn't get any response and I was not able to replicate this issue. 
please consider this issue as closed.

**Comment by dlra** [comment]
Apologies @iPazooki I was annual leave and then was sick so didn't have time to test properly and reply.. The package update cleared up the issue.

**Comment by iPazooki** [comment]
@dlra hope you are well now. Glad to hear it. Thanks
