### ISSUE TITLE
Abstract parent type cache invalidation issue on saving derived type object in form module 

### ISSUE THREAD

**Issue by waqasaziz-geeks** [Geeksltd/Olive#72]
I've two entities **Feedback** (parent abstract entity) and **TrainingFeedback** child (inheriting Feedback).  I've  a list module on Feedback entity listing all types of feedback which are not yet reviewed. List module has two buttons "Confirm" & "Consent". Clicking on Confirm button navigates user to a modal page which has a Form module of **TrainingFeedback**. 

On form page user can add extra comments for Training feedback and can save it as confirmed feedback. On saving this form I can see that database fields **IsConfirmed** is updated correctly. and state of concrete type (TrainingFeedback) object is also updated to true. 

However, when user gets redirected back to the list of feedback (which is a list module on Abstract class Feedback), it still shows the feedback as unconfirmed. Following statement returns one record which is incorrect as **IsConfirmed** column is set to 1 in database as well. 
 **await Database.Of<Feedback>().Where(f => !f.IsConfirmed)** // Returns once record because cache isn't  cleared. 

Above mentioned workflow works fine if I disable application cache.

**Comment by iPazooki** [comment]
@waqasaziz after your last saving method please add `await Database.Refresh();` and let me know if this fixes your issue!

**Comment by iPazooki** [comment]
@waqasaziz I have the same issue on the workflow project, I just wanted to make sure that you have the same issue as I had, OK it seems we have invalidation cache issue in the Olive. I'm going to fix it. Thanks.

**Comment by iPazooki** [comment]
@waqasaziz  would you mind just for one time, manually change controller file and in add method instead of `info.Item = await Database.Save(item);` use` await Database.Save(item, SaveBehaviour.BypassSaving);`
if this solved your problem please let me know.

**Comment by waqasaziz** [comment]
Hi @iPazooki 
Replacing info.Item = await Database.Save(item); with  await Database.Save(item, SaveBehaviour.BypassSaving); didn't solve cache issue.

**Comment by iPazooki** [comment]
@waqasaziz  do you still experience this issue? I believe @PaymonK  has fixed this issue. if you don't experience this issue any more please let Paymon know and close this issue.
