### ISSUE TITLE
Log file name

### ISSUE THREAD

**Issue by j-lustig** [Geeksltd/Olive#75]
https://github.com/Geeksltd/Olive/blob/92f307a96657bb1ad5e2e745ac7fcd680691ef51/Olive/Logging/FileLogger/FileLoggerProvider.cs#L31

The year is not set correctly in the file name and creates files in the format `YYYY0911.txt`. The y's should be lower case to input the year correctly to the file name.

Thanks

**Comment by iPazooki** [comment]
@j-lustig Thanks for letting me know. yeah, you are right. we will fix it soon.

**Comment by iPazooki** [comment]
@PaymonK  please close this issue.
