### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/Olive#83]
For sending emails: https://geeksltd.github.io/Olive/#/Services/Email

- Under 'Sending Email` section, you have documented how to create the EmailMessage class manually. 
   - Instead, show the M# code to define the entity. BTW it should be marked as SoftDeleted.
   - Also you're not showing how to actually send an email, which is by inserting an EmailMessage instance to the database.
- The same goes for EmailTemplate (by the way rename MailTemplate to EmailTemplate).
- Above the Email template section, add a header, explain what it is and the way it's meant to be used.
- In code snippets, use ```csharp instead of ```c#
- The purpose of the last paragraph is not clear. 

@iPazooki

**Comment by PaymonK** [comment]
The same for SMS

**Comment by iPazooki** [comment]
@PaymonK I believe this issue is solved by #85 . if you don't mind please close it.
