### ISSUE TITLE
Global search

### ISSUE THREAD

**Issue by ManiAtGeeks** [Geeksltd/Olive#87]
- Add a the header to allow Global searching on all of the applications. 
- This should behave like the existing global search that we use on Geeks hub.
- This will use the existing module and add that to the default M# template.

**Comment by PaymonK** [comment]
Although the plugin supports multiple data sources, but the default implementation can have only one source which is a custom WebApi within the same project. 

There is no need to look for Services.xml or any other hub-specific stuff.

**Comment by iPazooki** [comment]
@PaymonK , I have used default implementation that looks for this path `api/global-search?searcher=[query]`. but it necessitates us to implement `Process` method as shown like below:
```csharp
    public class GlobalSearchSource : SearchSource
    {
        public override Task Process(ClaimsPrincipal user)
        {
             //Here we need to find all available URLs
        }
    }
```

but here we need to find a way to return all available paths. however, I could not find a way that M# let me extract all available URLs of the application.

**Comment by PaymonK** [comment]
There is just one path, which is hardcoded in that scenario.
That's fine.

**Comment by PaymonK** [comment]
The multiple url model is used for micro-services only.
