### ISSUE TITLE
Actions in the list

### ISSUE THREAD

**Issue by ManiAtGeeks** [Geeksltd/Olive#88]
**To add a column css (called : multi-action) then using javascript render the links as a drop down list items.**

To allow the developers to develop action columns using M# in the exact same way as before.

What this currently would produce in CSS would look like attachment 1, it contains multiple columns (one for each action) and can become far to long if for example there was 30 possible actions.

The improvement will allow the developers to develop in the exactly the same way as before, but instead the CSS would add only one column (called: multi-action) and then using Javascript will render the links as a drop down list of actions. This will look like this or in in attachment 2.

![old action list](https://user-images.githubusercontent.com/24550276/45891396-61ad0e00-bdbd-11e8-86bf-4be370a24424.png)

![new action list](https://user-images.githubusercontent.com/24550276/45891397-61ad0e00-bdbd-11e8-8abd-cd56e05a2e4a.png)

**Comment by iPazooki** [comment]
@PaymonK I need some clarification here, is it supposed to transform from _attachment 1_ to _attachment 2_ with **CSS** and **Javascript**?

I believe that **M#** will generates the table columns per each action and you want me to find any action buttons and merge them in a drop-down list?

**Comment by PaymonK** [comment]
That's not a clear example. What we need is this:
- Upon olive page initialization in javascript, select every <tr>, and inside it:
- Find all <TD> tags in that <TR> which have css class of 'action-button'.
- If you found any, then remove all the <TD> tags except the last one, and move the contents of all of them into that one remaining cell. There, generate a *drop down menu* and add each button as one child of the menu.
