### ISSUE TITLE
Validation prompts on drop down fields remain on screen

### ISSUE THREAD

**Issue by MohammadArifGeeksLtd** [Geeksltd/Olive#93]
![2018-09-26 11_03_39-window](https://user-images.githubusercontent.com/43604517/46074420-76075700-c17f-11e8-96e7-6386b1a4af8e.png)

When a validation prompt appears on a drop down field, it remains on screen even after the user has selected an option (see screenshot).

**Comment by iPazooki** [comment]
@PaymonK , This issue has been solved, please close this one.

**Comment by MohammadArifGeeksLtd** [comment]
Tested this and it is now working with latest olive.mvc updated in bower.json.
