### ISSUE TITLE
Validation prompt from a field that was displayed but then hidden still appears on screen

### ISSUE THREAD

**Issue by MohammadArifGeeksLtd** [Geeksltd/Olive#94]
There is a specific page where selecting a specific radio button will display a specific field. This newly displayed field has a mandatory validation referring to an integer (see screenshots)

When Layout type is set to Defects, a field called 'Number of defects' appears. Entering a string into this field and clicking Save will display a prompt stating 'Number of defects should be 0 or more'. If the user now changes the Layout type to Reports, the 'Number of defects' field is hidden and replaced by 'Days left until report expires' but the validation prompt stating 'Number of defects should be 0 or more' is still present on screen.

![2018-09-26 11_12_07-window](https://user-images.githubusercontent.com/43604517/46074515-bc5cb600-c17f-11e8-878a-7b869c5d7b84.png)
![2018-09-26 11_13_26-window](https://user-images.githubusercontent.com/43604517/46074521-bf57a680-c17f-11e8-9c96-2b85a84a7fbf.png)

**Comment by iPazooki** [comment]
@MohammadArifGeeksLtd  Thanks for letting me know, I'm going to fix it.

**Comment by MohammadArifGeeksLtd** [comment]
Updated olive.mvc in bower.json and this is now working correctly. Closing this issue
